name: sharly_app_light
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  window_manager: ^0.3.4
  freezed:
  freezed_annotation: ^2.1.0

  provider: ^6.0.4

  workmanager: ^0.5.1
  mqtt_client: ^9.6.1

  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^14.1.0

  fl_chart: ^0.61.0
  uuid: ^3.0.6

  http: ^1.0.0

  collection: ^1.17.1

  shared_preferences: ^2.0.13

  json_annotation: ^4.8.1
  async: ^2.10.0
  intl: ^0.18.0
  intl_translation: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  icons_launcher: ^2.1.0

flutter:
  uses-material-design: true
  generate: true


targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true

flutter_icons:
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  ios: true
  windows:
    generate: true
  image_path: "assets/icon.png"

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/logo_small.png"
    ios:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true
    macos:
      enable: true


msix_config:
  display_name: Sharly App
  publisher_display_name: KogniHome
  identity_name: com.kognihome.sharly-app
  msix_version: 0.0.0.1
  logo_path: assets/logo.png
  capabilities: internetClient
  output_path: "./installers"